[package]
name = "pn532"
version = "0.1.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>"]

[features]
with_i2c = ["i2cdev"]
debug_communication = []

[dependencies]
i2cdev = { version = "0.5.1", optional = true }

[dev-dependencies]
assert_matches = "1"
